---
ID: "025a872f-7bba-4f38-8a5b-a1521b81b2d1"
Parent: "a0e9eb1a-242b-4ff4-b5d5-c07cc626fcf1"
Template: "a0e9eb1a-242b-4ff4-b5d5-c07cc626fcf1"
Path: "/sitecore/templates/Project/industry-verticals/Components/Global Elements/Footer/Rendering Parameters/Footer Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0ae839c0-43e9-480d-85b8-fcfc83f9bfd2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jeral.sandeeptha@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250827T081654Z
