---
ID: "56a1d516-1b59-4db3-be21-5f9ed7b8d456"
Parent: "3dd5dfcc-0769-4306-9877-71df72ff22c5"
Template: "3dd5dfcc-0769-4306-9877-71df72ff22c5"
Path: "/sitecore/templates/Project/industry-verticals/Custom Templates/Products/Product Sizes/Product Size/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T111721Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "69d6c5a5-48c5-4a57-9b5e-24db9f072c08"
    - ID: "91a5f0ce-60e5-494d-ac50-9308b916b490"
      Hint: ProductSize
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251117T111726Z
