---
ID: "bbf22587-dd0f-402c-b451-482b3614a53a"
Parent: "24ca3990-e0ac-44b4-9143-28c0d149e027"
Template: "24ca3990-e0ac-44b4-9143-28c0d149e027"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Social Feed/Rendering Parameters/SocialFeed Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4fcd7e2a-6592-46e1-b4fd-6b88f82a4c07"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250915T093756Z
