---
ID: "dd91f390-7745-4dc2-ba2d-079d4747f7af"
Parent: "5b7afa46-1e81-47c1-97d6-f22d020535c0"
Template: "5b7afa46-1e81-47c1-97d6-f22d020535c0"
Path: "/sitecore/templates/Project/industry-verticals/Components/Products/Product Details/Rendering Parameters/Product Details Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c33154dd-c240-4384-89e4-557a5f9e8ac6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250924T084706Z
