---
ID: "aad323bd-297c-45bf-b409-b3e9db280c53"
Parent: "dc8c91e0-6348-4292-95c6-b491d6bc7921"
Template: "dc8c91e0-6348-4292-95c6-b491d6bc7921"
Path: "/sitecore/templates/Project/industry-verticals/Components/Global Elements/Header Extended/Header Extended Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {6B107FCC-05D3-4193-BE89-F025632BD8B6}
    {DC8C91E0-6348-4292-95C6-B491D6BC7921}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "01236e59-6866-472c-82f9-05289d45bed2"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "333b7d95-d586-4ee8-8d5d-f7a6ee3d0a9b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251117T110425Z
