---
ID: "dbaa108f-ff38-48db-afeb-0c57d36bffab"
Parent: "458caf7e-8f04-4696-9bc5-b725bb2e0211"
Template: "458caf7e-8f04-4696-9bc5-b725bb2e0211"
Path: "/sitecore/templates/Project/industry-verticals/Components/Doctors/Doctor Details/Rendering Parameters/Doctor Details Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "36d55bcd-f3b8-4350-9a61-a8ee72881979"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251114T110937Z
