---
ID: "b1d31119-842e-4467-ae0c-596eae4768fa"
Parent: "b67bef9a-ec18-4cec-9334-5ba4218a541b"
Template: "b67bef9a-ec18-4cec-9334-5ba4218a541b"
Path: "/sitecore/templates/Project/industry-verticals/Components/Navigation/SocialFollow/Rendering Parameters/SocialFollow Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "921775f7-1c24-4c8b-8840-ff8d6709d664"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\isuru.bandara@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250827T102906Z
