---
ID: "5f55c6dd-a038-4500-a63e-94458479f194"
Parent: "5c53a448-0af8-4595-ae6a-67a10ff88ac1"
Template: "5c53a448-0af8-4595-ae6a-67a10ff88ac1"
Path: "/sitecore/templates/Project/industry-verticals/Custom Templates/Products/Product Sizes/Product Size Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {3DD5DFCC-0769-4306-9877-71DF72FF22C5}
    {5C53A448-0AF8-4595-AE6A-67A10FF88AC1}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "1c8ad4c2-8d6d-4a67-ac6d-7ba431833a5c"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "55d8051e-235d-4e5b-9ffe-1652ff3ef623"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250922T101134Z
