---
ID: "bf75d4d5-5d2e-47d2-82b5-78b429b11ca0"
Parent: "977db802-52ad-4f8d-8a1e-1a677e4b2caf"
Template: "977db802-52ad-4f8d-8a1e-1a677e4b2caf"
Path: "/sitecore/templates/Project/industry-verticals/Components/Navigation/Breadcrumb/Rendering Parameters/Breadcrumb Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0bfdb127-32e1-484c-a43a-b0084c2afd84"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250901T223539Z
