---
ID: "7a7547cf-33b5-47d0-b935-5a821e1902fb"
Parent: "489fa1f2-d078-49ec-8891-b6696c4db073"
Template: "489fa1f2-d078-49ec-8891-b6696c4db073"
Path: "/sitecore/templates/Project/industry-verticals/Custom Templates/Products/Prodcut Categories/Product Category Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {5635EAAB-28A6-4783-A10E-C4F9B1B99BBA}
    {489FA1F2-D078-49EC-8891-B6696C4DB073}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "b2da2c0f-5532-401a-8d5d-ecf51d92eb11"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "735d3b55-ff0c-4b0f-8a54-06d96b58c422"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250922T085306Z
