---
ID: "a435247d-ad38-46db-9c9f-4356be2ed5f3"
Parent: "8fa0b406-061c-4f22-8a46-d8e804d0286a"
Template: "8fa0b406-061c-4f22-8a46-d8e804d0286a"
Path: "/sitecore/templates/Project/industry-verticals/Components/Products/Selected Products/Rendering Parameters/Selected Products Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3e713a52-b03b-4945-b681-9b0d5a6015fc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250925T124851Z
