---
ID: "40470ac3-5c1a-4583-9bd7-2792d18e61bd"
Parent: "38001de0-6d0b-4bc5-bf95-f616cfe0e281"
Template: "38001de0-6d0b-4bc5-bf95-f616cfe0e281"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Hero Banner/Hero Banner Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {AC18EEF2-F134-4985-8B74-6AD16CCA6577}
    {38001DE0-6D0B-4BC5-BF95-F616CFE0E281}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "c03f6872-53c5-4df6-a7e8-181bfdcf30cb"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "14b3839f-814a-4234-af44-6b08e19b4663"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250904T110536Z
