---
ID: "c2feb3fc-40f3-4d0e-9c3e-a7f09a8b5ea1"
Parent: "c9803292-dccc-4058-9bbe-d13ad084db59"
Template: "c9803292-dccc-4058-9bbe-d13ad084db59"
Path: "/sitecore/templates/Project/industry-verticals/Components/Navigation/SocialFollow/SocialFollow Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {F6930608-D385-4C04-9BB1-6D1053448867}
    {C9803292-DCCC-4058-9BBE-D13AD084DB59}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "2437e9ff-7244-4d48-8470-e2634af456c5"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2158cf76-3103-4ef8-a316-4ea5336e62b2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\isuru.bandara@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250827T102910Z
