---
ID: "4a8b0edd-1884-4bff-9acd-af4a303c81c1"
Parent: "b10ad02a-c9d2-47ca-8d8f-0684ad62b427"
Template: "b10ad02a-c9d2-47ca-8d8f-0684ad62b427"
Path: "/sitecore/templates/Project/industry-verticals/Components/Articles/Article Details/Rendering Parameters/Article Details Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3deed28c-587d-4aa8-85db-f80a49d18c6c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250912T093633Z
