---
ID: "04b004e6-983a-45fd-8a7e-317484a765a3"
Parent: "f1a250db-2caf-45dd-9ba5-0860a1ad7e45"
Template: "f1a250db-2caf-45dd-9ba5-0860a1ad7e45"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Hero Banner/Rendering Parameters/Hero Banner Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a348c0e1-f958-4fca-8547-47cb5b026297"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250904T110532Z
