---
ID: "23019649-0514-459d-b85c-a5cc6086f943"
Parent: "39bcc290-145f-42a7-ae9c-483f90b111d8"
Template: "39bcc290-145f-42a7-ae9c-483f90b111d8"
Path: "/sitecore/templates/Project/industry-verticals/Components/Global Elements/Header Extended/Rendering Parameters/Header Extended Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f0c73fac-5740-40ec-8f6e-5ba724edbb3c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251117T110420Z
