---
ID: "28ce5d92-3849-4557-b7b4-783e08dc6a85"
Parent: "8f2d81c4-5365-4423-a0cb-24f19d768baf"
Template: "8f2d81c4-5365-4423-a0cb-24f19d768baf"
Path: "/sitecore/templates/Project/industry-verticals/Components/Utilities/ThemeSwitcher/Rendering Parameters/ThemeSwitcher Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2adc6de9-86d5-43c6-9dfc-519ea0e190bb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jeral.sandeeptha@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251112T133523Z
