---
ID: "2b7a2a51-b934-4792-b5e5-236290e49335"
Parent: "1dff87f8-cd0b-4de1-9ad8-bb8f2ff71ea9"
Template: "1dff87f8-cd0b-4de1-9ad8-bb8f2ff71ea9"
Path: "/sitecore/templates/Project/industry-verticals/Components/Forms/Subscribe/Rendering Parameters/Subscribe Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c67f30c7-01f2-4ffb-b370-3bc53d475b30"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250904T075427Z
