---
ID: "206aa7c9-10e7-4867-b7fd-640931c197e8"
Parent: "718038ea-90ae-4868-b72f-33ecbe98c806"
Template: "718038ea-90ae-4868-b72f-33ecbe98c806"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Content Section/Rendering Parameters/Content Section Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0e42ca6a-cb2a-4fa5-9472-d1667441731c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251113T100222Z
