---
ID: "88fd8ee3-204e-4334-9dac-170468d16897"
Parent: "e3a40241-78da-4435-b1ab-b8c641f035d9"
Template: "e3a40241-78da-4435-b1ab-b8c641f035d9"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Promo/Rendering Parameters/Promo Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "92a264db-a0de-4592-a7c7-9a52e5b91bdd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\isuru.bandara@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250902T130952Z
