---
ID: "7cc78047-df62-461a-8e5a-8bf8c0e771c4"
Parent: "74ff7775-c239-43c5-ab2b-cab8e6ade96b"
Template: "74ff7775-c239-43c5-ab2b-cab8e6ade96b"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Offers/Rendering Parameters/Offers Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cc7c8e45-bff2-4bd7-9054-e5fae8181880"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250827T103454Z
