---
ID: "0177049b-5574-4040-9500-5b0d0d272186"
Parent: "337b3ecc-cd8e-4d23-bc43-13395ad3ada7"
Template: "337b3ecc-cd8e-4d23-bc43-13395ad3ada7"
Path: "/sitecore/templates/Project/industry-verticals/Components/Articles/Article Listing/Rendering Parameters/Article Listing Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7f6e9db5-be43-44cb-bd04-beb3a9e20c8d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250918T120705Z
