---
ID: "7a7bba4e-d76e-4e79-b632-a39f6c9dbacc"
Parent: "8f1478d4-3e78-4d50-b1d4-b8e282be7667"
Template: "8f1478d4-3e78-4d50-b1d4-b8e282be7667"
Path: "/sitecore/templates/Project/industry-verticals/Components/Navigation/NavigationIcons/Rendering Parameters/NavigationIcons Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c0f873b3-8a79-46fe-844d-5cb5ca337d09"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250827T073345Z
