---
ID: "6c951601-d172-4bb2-bbce-824374c8bbb4"
Parent: "5635eaab-28a6-4783-a10e-c4f9b1b99bba"
Template: "5635eaab-28a6-4783-a10e-c4f9b1b99bba"
Path: "/sitecore/templates/Project/industry-verticals/Custom Templates/Products/Prodcut Categories/Product Category/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T104816Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "771fb5a9-e04d-4bfc-9c27-dfb88f0b3913"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251117T104822Z
    - ID: "fe0c006b-d8ca-442a-943a-566a619d913c"
      Hint: CategoryName
      Value: $name
