---
ID: "09429e9d-c210-4fd8-852d-7adbb9dffe80"
Parent: "6ab9051b-06ac-481d-b44a-e08899368310"
Template: "6ab9051b-06ac-481d-b44a-e08899368310"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Page Header/Rendering Parameters/PageHeader Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211020T140508Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d64acadc-2c9f-4f27-aec0-fe6d62518863"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251110T131215Z
