---
ID: "8069ad16-8540-4722-aff5-96d53b118ba8"
Parent: "ceebf12e-c01a-4d9f-ab3e-ebb6bcb0c7de"
Template: "ceebf12e-c01a-4d9f-ab3e-ebb6bcb0c7de"
Path: "/sitecore/templates/Project/industry-verticals/Components/Page Content/Content Section/Content Section Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {076F38CA-9483-44EB-9B98-84FF808FDAFE}
    {CEEBF12E-C01A-4D9F-AB3E-EBB6BCB0C7DE}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "d5bf9c95-3e0d-4347-8755-b6bc06000dfd"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fb6a8d7d-471e-4264-a54d-7fe941da42e5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251113T100225Z
